[package]
name = "dzip-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dzip-core = { path = "../core" }
clap = { version = "4.6", features = ["derive"] }
anyhow = "1.0"
serde.workspace = true
toml = "1.1"
log.workspace = true
env_logger = "0.11"

rayon = "1.12"
indicatif = "0.18"
