[package]
name = "dzip-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
description = "Modern command-line builder, creator, extractor, and inspector for Dzip archives"
readme = "../../README.md"

[dependencies]
dzip = { workspace = true, features = ["parallel"] }
dzip-dcl.workspace = true
dzip-workflow = { workspace = true, features = ["dcl", "parallel"] }
clap = { version = "4.6.4", features = ["derive"] }
log.workspace = true
env_logger = "0.11"
