[package]
name = "dzip-gui-worker"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
description = "Web Worker runtime for Dzip Archive"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1"
dzip-workflow = { workspace = true, features = ["protocol"] }
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
